vitrivr/cineast

src/org/vitrivr/cineast/api/JSONAPIThread.java, src/org/vitrivr/cineast/api/JSONUtils.java, src/org/vitrivr/cineast/api/websocket/handlers/QueryMessageHandler.java, src/org/vitrivr/cineast/art/modules/VisualizationAverageColorStripeVariable.java, src/org/vitrivr/cineast/art/modules/VisualizationDominantColorStripeVariable.java, src/org/vitrivr/cineast/art/modules/VisualizationMedianColorStripeVariable.java, src/org/vitrivr/cineast/core/db/dao/reader/SegmentLookup.java, src/org/vitrivr/cineast/core/features/VideoMetadata.java, src/org/vitrivr/cineast/core/features/listener/RetrievalResultEvaluationExporter.java, src/org/vitrivr/cineast/core/run/filehandler/AbstractExtractionFileHandler.java, src/org/vitrivr/cineast/core/util/ArtUtil.java
Refactored SegmentLookup:
- Changed signature for sake of clarity (`lookUpAllSegments` -> `lookUpSegmentsOfObject`)
- Removed code duplication regarding lookup; introduced generalized lookup method
- Removed code duplication regarding `PrimitiveTypeProvider`
- Added new method `lookUpSegmentsOfObjects`
=> Refactored SegmentLookup

src/org/vitrivr/cineast/api/API.java, src/org/vitrivr/cineast/core/data/entities/MultimediaMetadataDescriptor.java, src/org/vitrivr/cineast/core/db/dao/reader/MultimediaMetadataReader.java, src/org/vitrivr/cineast/core/features/SpatialDistance.java, src/org/vitrivr/cineast/core/metadata/EXIFMetadataExtractor.java, src/org/vitrivr/cineast/core/metadata/JsonMetadataExtractor.java
Cleaned up and did some refactoring regarding `MultimediaMetadataReader` and `MultimediaMetadataDescriptor`, in particular:
- Added an interactive API command to lookup metadata given object id(s)
- Significantly shortened the factory method name of MultimediaMetadataDescriptor
- Enabled code reuse for the `value` parsing
- Added a sensible `toString` method
- Removed code duplication regarding the lookup methods of `MultimediaMetadataReader` and added another variant using `Iterable`.
=> Cleanup regarding Metadata

cineast.json, src/org/vitrivr/cineast/core/data/GpsData.java, src/org/vitrivr/cineast/core/data/Location.java, src/org/vitrivr/cineast/core/data/messages/query/QueryTerm.java, src/org/vitrivr/cineast/core/data/query/containers/InstantQueryContainer.java, src/org/vitrivr/cineast/core/data/query/containers/LocationQueryContainer.java, src/org/vitrivr/cineast/core/features/abstracts/MetadataFeatureModule.java, src/org/vitrivr/cineast/core/util/MetadataUtil.java, src/org/vitrivr/cineast/core/util/json/JacksonJsonProvider.java, src/org/vitrivr/cineast/core/util/json/JsonReader.java, tests/org/vitrivr/cineast/core/data/LocationTest.java
This pull request adds query containers for spatial and temporal similarity queries based on a fixed location or a fixed instant, e.g.:
```
{
"types": ["IMAGE"],
"containers": [{
"terms": [
{
"categories": ["spatial"],
"type": "LOCATION",
"data": "[47.560356, 7.587264]" // or "{ 'latitude': 47.56, 'longitude': 7.58 }"
}, {
"categories": ["temporal"],
"type": "TIME",
"data": "2016-07-14T13:30:00Z"
}
]
}]
}
```
Main changes:
* Added `InstantQueryContainer` and `LocationQueryContainer`
* Extended conversion of `QueryTerm` to a `QueryContainer` to support location and instant
* Refactored some parts of `GpsData` to expose the parsing of location and instant
=> Added QueryContainers for Location and Instant

src/org/vitrivr/cineast/core/features/SpatialDistance.java, src/org/vitrivr/cineast/core/features/TemporalDistance.java, src/org/vitrivr/cineast/core/features/abstracts/MetadataFeatureModule.java, src/org/vitrivr/cineast/core/metadata/MetadataFeatureExtractor.java
Because the object id already gets extracted from the file using an `ObjectIdGenerator`, there is no reason to withhold this information from classes implementing `MetadataFeatureExtractor`.
Note that the current features implementing this interface do not make use of this.
=> Added objectId to signature of MetadataFeatureExtractor.extractFeature

src/org/vitrivr/cineast/core/run/ExtractionDispatcher.java
Currently, relative input paths of job files get resolved against the working directory of Java which is usually the top directory of Cineast. When working with multiple, different datasets or collections, this behaviour is usually restrictive because it does not allow to create job files with relative paths inside some other directory unrelated to Cineast.
This pull request changes the path resolution of a relative path to use the directory of the job file.
A common use case would be to create one directory for a collection with an accompanying job file, e.g.:
some-collection
├── image0001.jpg
├── image0002.jpg
├── image0003.jpg
├── image0004.jpg
⋮
├── movie0001.mp4
├── movie0002.mp4
├── movie0003.mp4
⋮
├── job.json
With this pull request, the job file can make use a relative path for …
=> Relative input paths now resolved against directory of job file

src/org/vitrivr/cineast/api/rest/RestfulAPI.java, src/org/vitrivr/cineast/api/websocket/WebsocketAPI.java, src/org/vitrivr/cineast/core/data/messages/general/AnyMessage.java, src/org/vitrivr/cineast/core/data/messages/general/Error.java, src/org/vitrivr/cineast/core/data/messages/general/Ping.java, src/org/vitrivr/cineast/core/data/messages/interfaces/Message.java, src/org/vitrivr/cineast/core/data/messages/interfaces/MessageType.java, src/org/vitrivr/cineast/core/data/messages/lookup/IdList.java, src/org/vitrivr/cineast/core/data/messages/lookup/MetadataLookup.java, src/org/vitrivr/cineast/core/data/messages/query/Query.java, src/org/vitrivr/cineast/core/data/messages/result/MetadataQueryResult.java, src/org/vitrivr/cineast/core/data/messages/result/ObjectQueryResult.java, src/org/vitrivr/cineast/core/data/messages/result/QueryEnd.java, src/org/vitrivr/cineast/core/data/messages/result/QueryStart.java, src/org/vitrivr/cineast/core/data/messages/result/SegmentQueryResult.java, src/org/vitrivr/cineast/core/data/messages/result/SimilarityQueryResult.java, src/org/vitrivr/cineast/core/data/messages/session/StartSessionMessage.java
* Renamed enum `MessageTypes` to `MessageType`
* Fixed method naming of `Message.getMessageType` (camelcase)
* Removed the ending slash of the Restful similarity query `find/segments/similar`
=> Small cleanup for messages

src/org/vitrivr/cineast/core/data/providers/SegmentProvider.java, src/org/vitrivr/cineast/core/db/ADAMproWrapper.java, src/org/vitrivr/cineast/core/db/NeuralNetLookup.java, src/org/vitrivr/cineast/core/db/dao/writer/AbstractBatchedEntityWriter.java, src/org/vitrivr/cineast/core/decode/general/Decoder.java, src/org/vitrivr/cineast/core/decode/video/VideoDecoder.java, src/org/vitrivr/cineast/core/segmenter/general/Segmenter.java, src/org/vitrivr/cineast/core/setup/EntityCreator.java
Multiple class and interfaces contained a `close` method but did not implement `AutoCloseable`. With this change, all of the affected classes/interfaces can now be used in try-with-resource constructs.
=> Added AutoCloseable to multiple classes and interfaces.

src/org/vitrivr/cineast/api/API.java, src/org/vitrivr/cineast/api/APIEndpoint.java, src/org/vitrivr/cineast/api/SessionExtractionContainer.java, src/org/vitrivr/cineast/api/rest/handlers/actions/session/StartExtractionHandler.java, src/org/vitrivr/cineast/core/run/filehandler/GenericExtractionItemHandler.java, src/org/vitrivr/cineast/core/run/path/SessionContainerProvider.java
* You need to use the UniqueIDGenerator if you're restarting sessions. The current implementation restarts the whole pipeline which means that a new IDGenerator is created, which results in the SequentialIdGenerator being unusable for this specific feature.
=> Restarting Sessions

src/org/vitrivr/cineast/core/data/entities/MultimediaMetadataDescriptor.java, src/org/vitrivr/cineast/core/db/dao/writer/MultimediaMetadataWriter.java, src/org/vitrivr/cineast/core/metadata/EXIFMetadataExtractor.java
If the given EXIF-Metadata value is a byte-array or something unsupported, it will now be ignored instead of throwing a RuntimeException
=> Filtering empty exif-values to prevent RTE

src/org/vitrivr/cineast/api/APIEndpoint.java, src/org/vitrivr/cineast/api/SessionExtractionContainer.java, src/org/vitrivr/cineast/api/rest/handlers/actions/FileExtractionHandler.java, src/org/vitrivr/cineast/core/run/ExtractionItemContainer.java
Add Media API is completely implemented. This implementation is different from the one I did previously. Main highlights are:
1) No need to start the cineast server with --server option along with a config file. When a request arrives, provider will be initialized/opened if closed, extraction will take place and then session will be ended so as to write data to ADAMPro.
2) Instead of starting cineast server with --server config, there must be 4 config files (for image, video, audio, 3d model) in the same directory as cineast.jar. This is done mainly because of three reasons.
i. If there is only one config files, all the exporters need to be specified (ShotThumbNails, AudioWaveformExporter, Model3DThumbnailExporter etc) for all different media types. The problem with this is if say an …
=> Implemented Add Media API.

src/org/vitrivr/cineast/api/APIEndpoint.java
Added `Access-Control-Allow-Headers: *` explicitely to the header in RESTful API.
In some circumstances of asnchronous calls, at least Google Chrome probes access control and requires this header to perform POST requests to the RESTful API.
=> Added response header in RESTful API to allow all headers

src/org/vitrivr/cineast/api/rest/handlers/actions/FindMetadataByObjectIdActionHandler.java, src/org/vitrivr/cineast/api/rest/handlers/actions/FindObjectByActionHandler.java, src/org/vitrivr/cineast/api/rest/handlers/actions/FindSegmentsByIdActionHandler.java
TL;DR Websocket and RESTful API now respond with the same JSON object's and lists are properly enclosed by an object.
The following is a copy of  sauterl/cineast@940f74c2ee13d78b8427c3de214e611189e23249 describing the consequences of the change:
---
Restored consistency in certain query responses
The WebSocket and RESTful API now returns the same JSON objects for
* /find/metadata/by/id
* /find/objects/by/id
* /find/segments/by/id
Each of the corresponding RESTful action handler's now do have the same result
type as the corresponding WebSocket handlers have.
The main advantage is that both APIs do now have similar response
objects.
Further, there is a minor advantage in not sending top level arrays: A
few JSON processors cannot handle such documents and would therefore not
be able to be …
=> Restored consistency in certain query responses

cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailSelector.java
A batched knn query is designed to return k*n results. Til now, k was set as query limit, so we always got the k nearest neighbours of the first provided segment only.
=> avoid getting first k of batched knn only

cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/DatabaseSetupCommand.java
This patch allows --extraction to be passed to setup to setup tables/entities from the extraction json instead of the cineast json, which could be convenient e.g. if you're doing a batch extraction of many features and you might expose a subset later on.
=> Allow extraction config to be passed to specify database entities to setup

cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/ExtractionContextProvider.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/config/IngestConfig.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/config/InputConfig.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/path/ExtractionContainerProviderFactory.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/path/TreeWalkContainerIteratorProvider.java
This helps with usage in which the extraction process is invoked multiple times for each file within a larger collection -- typically by templating the extraction config file.
=> Add relTo, allow file inputPath in extraction config

cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ExtractionCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/ExtractionCompleteListener.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/GenericExtractionItemHandler.java
See discussion in #121. If cottontail is not used, the `OptimizeEntitiesCommand` simply returns without doing anything.
=> Automatically executing optimize after extraction if no flag is set

cineast-api/src/main/java/org/vitrivr/cineast/api/APIEndpoint.java, cineast-api/src/main/java/org/vitrivr/cineast/api/websocket/WebsocketAPI.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/monitoring/PrometheusServer.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/runtime/ContinuousQueryDispatcher.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/util/ContinuousRetrievalLogic.java
Problems identified and fixed include:
- WebSocket ThreadPoolExecutor not being closed at shutdown (would prevent correct shutdown after established WebSocket connection)
- ContinuousRetrievalLogic resources not properly closed
- ThreadPoolExecutor in ContinuousQueryDispatcher not guaranteed to be shut down
=> Fixed Cineast sometimes not shutting down completely.

cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/ExtractionContextProvider.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/config/IngestConfig.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/config/InputConfig.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/ExtractionDispatcher.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/GenericExtractionItemHandler.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/path/ExtractionContainerProviderFactory.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/path/TreeWalkContainerIteratorProvider.java
- Implemented skipping of directory paths during extraction, since the directory files themselves are not processed by any extractors and only print unsupported file type debug messages
- Removed unused and deprecated fields in InputConfig
- Removed some empty Javadoc comments and minor cleanup
=> Extraction improvements

cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/util/CLI.java
Added "stop" and the end-of-file character ^D as Cineast API CLI exit methods.
=> API CLI exit improvements

cineast-core/src/main/java/org/vitrivr/cineast/core/data/query/containers/ImageQueryContainer.java, cineast-core/src/main/java/org/vitrivr/cineast/core/data/query/containers/ModelQueryContainer.java, cineast-core/src/main/java/org/vitrivr/cineast/core/data/raw/CachedDataFactory.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/config/Config.java
Use the cache key of whichever sharedConfig has been loaded last to
provide the configuration for the default CachedDataFactory instance
Closes #113
=> Make default cache location configurable

cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailEntityCreator.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailWrapper.java
Otherwise I get a bunch of log messages like these:
```
2020-08-13 10:44:52 ERROR CottonDDLService:37 - Error while creating schema
org.vitrivr.cottontail.model.exceptions.DatabaseException$SchemaAlreadyExistsException: Schema 'warren.cineast' does already exist!
at org.vitrivr.cottontail.database.catalogue.Catalogue.createSchema(Catalogue.kt:121)
at org.vitrivr.cottontail.server.grpc.services.CottonDDLService.createSchema(CottonDDLService.kt:33)
at org.vitrivr.cottontail.grpc.CottonDDLGrpc$MethodHandlers.invoke(CottonDDLGrpc.java:1055)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
at …
```
=> Stop new CottontailEntityCreators flooding Cottontail new schema creations

cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/video/VideoHistogramSegmenter.java
This allows me to make sure segments don't end up too long, as a sort of mitigation of https://github.com/vitrivr/cineast/issues/123
=> Make threshold/maxShotLength of VideoHistogramSegmenter configurable

cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ExtractionCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ImportCommand.java
Running import without type or input arguments would cause a NullPointerException and crash the CLI.
Fixed to only print a descriptive error message and return to the CLI.
=> Import command safety

Dockerfile, README.md, hooks/post_checkout
I have been using my own Singularity recipe up until now but:
1. Building Docker images on Docker Hub for use with Singularity seems to actually be a better option in many cases than using Singularity + SingularityHub (more info: https://github.com/frankier/gsoc2020/wiki/Should-you-avoid-using-Singularity-and-Singularity-Hub-to-build-your-Singularity-images%3F )
2. Docker is commonplace so this is presumably more useful to others
3. Docker Hub makes it easy for everyone to get autobuilds of their own branches/PRs
This exposes a custom entrypoint so we can choose to use either `docker run cineast api` or `docker run cineast cli` to run either the server+repl or the cli.
Ready to merge if the Docker Hub build works https://hub.docker.com/repository/registry-1.docker.io/frankierr/cineast/buil …
=> Add dockerfile

cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ExtractionCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/ExtractionDispatcher.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/ExtractionItemProcessor.java
Implemented blocking in the extraction command.
The extraction command was previously run independently on a separate thread, which allowed other commands to be run from the CLI in parallel, potentially causing problems. This commit introduces a blocking call so that the main thread responsible for the CLI waits to join the extraction thread.
=> Extraction blocking

cineast-core/src/test/java/org/vitrivr/cineast/core/db/DBIntegrationTest.java
In DBIntegrationTest class, the name of a string constant "hello world my name is cineast" is misleading. I changed it from "HELLO_MY_NAME_IS_CINEAST_ID" to "HELLO_WORLD_MY_NAME_IS_CINEAST_ID".
=> Change the name of a variable for easy reading.

cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/IIIFConfig.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/discoveryapi/v1/OrderedCollectionFactory.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/discoveryapi/v1/OrderedCollectionRequest.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/discoveryapi/v1/models/IdTypeObject.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/discoveryapi/v1/models/OrderedCollection.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/discoveryapi/v1/models/OrderedCollectionPage.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/discoveryapi/v1/models/OrderedItem.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ExtractionCommand.java, example_iiif_job.json
This allows Cineast to download images from the manifests on a Discovery API change. Currently only Ordered Items with the `type` value of `Create` will be processed.
~~This PR is based on #217  and should be merged only once it has been merged into the codebase.~~
~~To see a diff of this PR and #217, see https://github.com/singaltanmay/cineast/pull/12/files~~
=> Partial implementation of IIIF Change Discovery API 1.0

build.gradle
JCenter is currently down, which has led to me discovering that we should not be using it anymore anyway: https://blog.gradle.org/jcenter-shutdown
=> HOTFIX: removing jcenter from repositories

cineast-core/src/main/java/org/vitrivr/cineast/core/features/VisualTextCoEmbedding.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/abstracts/MotionHistogramCalculator.java
Implemented the extraction of the visual-text co-embedding feature for videos, such that not only the most representative frame for each shot is considered, but all frames mean-pooled in the encoding space.
Additional minor cleanup refactoring in the MotionHistogramCalculator.
=> Visual-text co-embedding video extraction

build.gradle, cineast-core/src/main/java/org/vitrivr/cineast/core/data/providers/primitive/PrimitiveProviderComparator.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/imageapi/ImageApiVersion.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/imageapi/ImageFactory.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/imageapi/ImageInformation.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/imageapi/v2/ImageInformation_v2.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/presentationapi/v2/models/Manifest.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/presentationapi/v2/models/Metadata.java, cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/presentationapi/v2/models/Structure.java, cineast-core/src/main/java/org/vitrivr/cineast/core/util/MultiTracker.java, cineast-core/src/main/java/org/vitrivr/cineast/core/util/json/JacksonJsonProvider.java
Fixes all but two of the Java build warnings to make it easier to see if code changes produce new build warnings.
The remaining two build warnings could not be resolved because they either require a change in an external library (Cottontail DB Client) or are unclear in the intent of the original code.
=> Fix Java build warnings

build.gradle, cineast-core/src/main/java/org/vitrivr/cineast/core/config/DatabaseConfig.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/dao/writer/MediaObjectMetadataWriter.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/dao/writer/MediaObjectWriter.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/dao/writer/MediaSegmentWriter.java
**Changes:** 
- Initialisation of Writers now takes place in construction
- DatabaseConfig.getSelectorSupplier() now respects selector config instead of writer config.
=> Fixed two issues related to feature extraction

build.gradle, cineast-api/src/main/java/org/vitrivr/cineast/api/messages/query/TemporalQuery.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/dao/MetadataAccessSpecification.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/dao/reader/AbstractMetadataReader.java
To be backward-compatible, the implementation of the `MetadataAccessSpecification` returned all metadata if the field was not set in a query. However, the intention (and what this PR fixes) was that if an empty List is provided, no metadata is returned. This saves execution time for queries which do not care about metadata.
=> Returning no Metadata if Metadata Spec is Empty

cineast-api/src/main/java/org/vitrivr/cineast/api/messages/query/TemporalQuery.java, cineast-api/src/main/java/org/vitrivr/cineast/api/messages/query/TemporalQueryConfig.java, cineast-api/src/main/java/org/vitrivr/cineast/api/websocket/handlers/queries/TemporalQueryMessageHandler.java
Outsourcing config values only relevant for temporal queries into a separate config. Corresponding PR for vitrivr-ng: https://github.com/vitrivr/vitrivr-ng/pull/117
=> Temporal Query Config

build.gradle, cineast-core/src/main/java/org/vitrivr/cineast/core/db/DBSelector.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailSelector.java
The `DBSelector` Interface had two abstractions for nearest-neighbor search, one of which only returns ids & distances, the other one returns the full row. The second one is used e.g by the `AverageColorRaster` Feature which has the schema `id`, `hist`, `raster` and requires the raster for score-computation. 
This PR fixes the cottontail implementation to avoid NPEs in `AverageColorRaster`. Thanks to @benzvera for pointing out the bug.
It also optimizes the `countDistinctValues` command, which only needs to retrieve the column for which it counts distinct values.
=> Fixing NearestNeighborRows only returning id column

cineast-api/src/main/java/org/vitrivr/cineast/api/util/QueryUtil.java
In rare cases, the `segmenttags` entity is not available when an API request is made. In this case, Cineast after this PR simply returns an empty String instead of failing the entire request.
=> improving robustness when feature entity is missing

cineast.json
This makes it so the default config works out of the box. The config example for the RangeBooleanRetriever is documented on the wiki: https://github.com/vitrivr/cineast/wiki/Useful-Config-Hints.
This is done in the context of https://github.com/vitrivr/vitrivr-ng/pull/124, where the corresponding functionality is added to frontend.
=> Adding Working CollectionBooleanRetriever to Default Config

cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailWriter.java
The issue is caused by the absence of a transaction ID for subsequent `BatchInsert` objects, which leads to a concurrent write transaction that is blocked bythe transaction initiated before.
=> Fixed issue that would cause a deadlock during batch inserts.

cineast-api/src/main/java/org/vitrivr/cineast/api/APIEndpoint.java, cineast-api/src/main/java/org/vitrivr/cineast/api/rest/handlers/actions/feature/FindFeaturesByCategoryPostHandler.java, cineast-api/src/main/java/org/vitrivr/cineast/api/rest/handlers/actions/feature/FindFeaturesByEntityPostHandler.java, docs/openapi.json
When using the API endpoints, it was noticed that two POST handlers were named GET handlers (FindFeaturesByCategoryGetHandler and FindFeaturesByEntityGetHandler). This naming issue is fixed with this commit. At the same time, the OpenApiSpecs were rebuilt.
However, the functionality of Cineast has not changed.
=> Refactoring of POST handlers

hooks/post_checkout
Since there are no more submodules, this hook is not needed anymore
=> Removing unneeded post_checkout hook

build.gradle, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/Main.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/AbstractCineastCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/CineastCli.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/CodebookCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/DatabaseSetupCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/DistinctColumnApiCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ExtractionCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ImportCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/OptimizeEntitiesCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/RetrieveCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/SingleObjRetrievalCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/TagRetrievalCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/TextRetrievalCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ThreeDeeTestCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/db/DropTableCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/db/PolyphenyBenchmarkCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/util/CLI.java
Addresses #306 by slightly refactoring the current command hierarchy and introducing the following behaviour:
When the `-h` (or `--help`) option is given for a command (i.e. `<dist> path/to/config.json <command> -h`),
the missing required options are listed and then the help message is shown on std err.
For the interactive CLI, the same logic applies, however the information is printed on std out with the colour red.
**Important: This PR already contains the next version bump**
=> Standalone commands / CLI respect -h / --help for help

build.gradle, cineast-core/src/main/java/org/vitrivr/cineast/core/features/CLIPImage.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/CLIPText.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/SkeletonPose.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/VisualTextCoEmbedding.java
- Ensuring models are only loaded once through synchronized static methods.
- Ensuring the SkeletonPose model is only loaded when needed for extraction and not for retrieval.
Closes #303.
Closes #311.
=> Fixed model loading.

.github/workflows/codeql-analysis.yml, .github/workflows/gradle.yml, build.gradle
Additionally, bumping to v3.12.0 so we can create a new release based on the new head commit hash
=> Fixing CI branch names

cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailWriter.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/AudioTranscriptionSearch.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/CollectionBooleanRetriever.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/ProvidedOcrSearch.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/RangeBooleanRetriever.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/SkeletonPose.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/SpatialDistance.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/SubtitleFulltextSearch.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/abstracts/AbstractTextRetriever.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/CliUtils.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/TagRetrievalCommand.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/TextRetrievalCommand.java
Some time ago, each term used to be decorated with `~` at the end for fuzzy matches. This got lost at some point, which leads to a query for `JAMES` to not match `AMES` in an OCR column. To fix this, this PR adds configurable decorators for all text-retrieval classes. Default behavior stays the same.
Additionally, it adds the option to configure entity-names for text retrieval classes and fixes rare edge-cases where batch-import would cause problems.
=> Making decorator for text retrieval configurable

cineast-core/build.gradle
Fixes #313.
Tested to work as expected with builds on macOS and Ubuntu.
=> Implemented OS switch so macOS builds use CPU version of TensorFlow.

cineast-core/src/main/java/org/vitrivr/cineast/core/util/ReflectionHelper.java
Changes in #324 made all constructors take `Map` as parameter if there are properties. However, this requires explictly searching for `Map` as class type in reflection. If this is not done, an exception is thrown:
```
2022-07-26 07:55:04.238 [ssq-0] ERROR o.v.c.c.u.ReflectionHelper - java.lang.NoSuchMethodException: org.vitrivr.cineast.core.features.ProvidedOcrSearch.<init>(java.util.LinkedHashMap)
at java.base/java.lang.Class.getConstructor0(Class.java:3585)
at java.base/java.lang.Class.getConstructor(Class.java:2271)
at org.vitrivr.cineast.core.util.ReflectionHelper.instantiate(ReflectionHelper.java:285)
at org.vitrivr.cineast.core.util.ReflectionHelper.instantiate(ReflectionHelper.java:272)
``` 
This PR fixes that by explictly searching for Map constructors if there is a map passed.
=> Explicitly specifying type as Map for constructors

build.gradle, cineast-core/src/main/java/org/vitrivr/cineast/core/features/VisualTextCoEmbedding.java
Previously the visual-text co-embedding only allowed retrieval with text terms and would even retrieve using the empty string provided by default if no text term was specified.
This has been fixed with appropriate error messages and returns.
Retrieval using image terms was implemented.
=> Visual-Text Co-Embedding image retrieval

cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailSelector.java, cineast-core/src/test/java/org/vitrivr/cineast/core/db/DBBooleanIntegrationTest.java
Speeding up text retrieval by preventing text being sent back from cottontail. 
Specifically, previously Cottontail sent back the distance twice and the full text which was stored. Now, only id + distance are sent.
=> Preventing unnecessary data being sent for text queries

cineast-core/src/main/java/org/vitrivr/cineast/core/features/exporter/ShotThumbnailsExporter.java
Fixed ShotThumbnailsExporter not working due to HashMap/Map reflections mismatch. Resolves #337
=> Fixed ShotThumbnailsExporter.

Dockerfile
See notice on https://hub.docker.com/_/openjdk
Alternatively you could also use the `gradle:jdk17` image to avoid downloading gradle on every build.
=> Switch from deprecated openjdk to eclipse-temurin base

gradle.properties
This reduces the build time of `shadowJar` by 50~65% on my end (using Docker, no caching involved). However, fetching and compressing `externalFiles` is still the most time consuming task.
=> Enable Gradle parallel builds

cineast-api/src/main/java/org/vitrivr/cineast/api/Main.java
This PR fixes #349. It does not interfere with the aim of #345, as there is a while(true) loop if the CLI is not enabled.
=> Fixing CLI not exiting properly

cineast-core/src/main/java/org/vitrivr/cineast/core/features/exporter/Model3DThumbnailExporter.java
Fixed Model3DThumbnailExporter not working due to HashMap/Map reflections mismatch.
Similar to #337
=> Fixed HashMap Bug in Model3DThumbnailExporter

cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/audio/ConstantLengthAudioSegmenter.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/general/Segmenter.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/image/ImageSegmenter.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/image/ImageSequenceSegmenter.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/video/ConstantLengthVideoSegmenter.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/video/TRECVidMSRSegmenter.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/video/V3CMSBSegmenter.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/video/VideoHistogramSegmenter.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/GenericExtractionItemHandler.java
Previously, the GenericExtractionItemHandler did not respect the config-provided segmenter, which is being fixed by this PR.
If no segmenter is specified, reasonable defaults are used per media type, this logic was not changed.
=> Fixed #353 by respecting config value for segmenter

cineast-core/src/main/java/org/vitrivr/cineast/core/data/entities/MediaObjectDescriptor.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/idgenerator/FileNameObjectIdGenerator.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/idgenerator/JSONProvidedObjectIdGenerator.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/idgenerator/ObjectIdGenerator.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/idgenerator/SequentialObjectIdGenerator.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/idgenerator/Sha1ObjectIdGenerator.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/idgenerator/UniqueObjectIdGenerator.java, cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/image/ImageSequenceSegmenter.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/GenericExtractionItemHandler.java
Motivated by my review #360, I refactored and cleaned up the existing object id generators.
- Using `Optional` instead of "null" as a string (!)
- Removed unused code
- Using `getOrDefault` instead of more verbose code
- Throwing exceptions instead of generating objects with `null` as id.
=> Refactoring Object Id Generation

cineast-api/src/main/java/org/vitrivr/cineast/api/Main.java, cineast-core/src/main/java/org/vitrivr/cineast/core/util/CineastConstants.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/Main.java, cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/config/Config.java
Based on #363, if no config path is provided & no config file is available, the behavior is inconsistent in that Cineast does not shut down but proceeds.
This change makes sure the behavior is consistent
=> Improved error message when no config is available

cineast-core/src/main/java/org/vitrivr/cineast/core/db/DBSelector.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/ImporterSelector.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/NoDBSelector.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailSelector.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/dao/reader/AbstractMetadataReader.java, cineast-core/src/main/java/org/vitrivr/cineast/core/db/polypheny/PolyphenySelector.java, cineast-core/src/main/java/org/vitrivr/cineast/core/features/RangeBooleanRetriever.java, cineast-core/src/test/java/org/vitrivr/cineast/core/db/DBBooleanIntegrationTest.java
This PR unifies variable names & cleans up documentation in the `DBSelector` in preparation on upcoming work for multi-collection support.
Specifically, it adds query-configs to most retrieval methods where they were not already present, adds SQL-Like documentation to methods, cleans up unused code, makes clear which methods are convenience methods and which can be overriden by underlying implementations for performance-gains.
=> DBSelector Documentation Updates

cineast-runtime/src/main/resources/log4j2.xml
Uses `LOG_LEVEL` to configure log level. Default changed to `INFO`.
=> Make log level configurable (#377)
