vitrivr/cineast

src/org/vitrivr/cineast/api/API.java

Fixed the NullPointerException when using the setup option of the API. Additionally, the option now supports no value as well, i.e. an optional argument.

Fixed NullPointerException when using "--setup".

---

src/org/vitrivr/cineast/core/util/json/JacksonJsonProvider.java

Moved the logging of the exceptions in `JacksonJsonProvider` into own method.

Refactored exception logging of JacksonJsonProvider

---

src/org/vitrivr/cineast/core/metadata/EXIFMetadataExtractor.java
src/org/vitrivr/cineast/core/util/images/MetadataUtil.java

Created `MetadataUtil` for accessing metadata `Directory`s. Refactored `EXIFMetadataExtractor` accordingly to make use of the class and also made it functional...

Moved Metadata extraction into own class

---

src/org/vitrivr/cineast/core/config/deserializers/FeatureCategoriesDeserializer.java

Also added a more detailed error message if instantiation fails.

Enabled fully qualified class name for Retrievers

---

src/org/vitrivr/cineast/core/features/SpatialDistance.java

Changed the correspondence function of `SpatialDistance` to a hyperbolic function with the following scaling:
* 37m = 90%
* 333.3m = 50%
* 3000m = 10%

Hyperbolic correspondence for SpatialDistance

---

README.md

The Travis CI in the README was linking to Ralph's Repo

Fixing Travis Link

---

gradle/wrapper/gradle-wrapper.properties
settings.gradle

To 4.1, also adding settings.gradle file

Gradle upgrade

---

src/org/vitrivr/cineast/core/config/RetrieverConfig.java
src/org/vitrivr/cineast/core/util/ContinuousRetrievalLogic.java

Could be easily extendable to query for one retriever instance

Adding Logic to retrieve for one single feature by Name

---

README.md

added recursive flag to clone command in readme

---

src/org/vitrivr/cineast/api/SessionExtractionContainer.java
src/org/vitrivr/cineast/api/rest/handlers/actions/session/ExtractItemHandler.java
src/org/vitrivr/cineast/api/rest/handlers/actions/session/StartExtractionHandler.java
src/org/vitrivr/cineast/core/run/filehandler/GenericExtractionItemHandler.java
src/org/vitrivr/cineast/core/run/path/SessionContainerProvider.java
src/org/vitrivr/cineast/core/runtime/ExtractionTask.java

* Default 3D Segmenter
* Logging cleanup and documentation improvements

Generic Extraction Upgrades

---

build.gradle
cineast.json
generated/main/java/ch/unibas/dmi/dbis/cottontail/grpc/CottontailGrpc.java
src/org/vitrivr/cineast/api/API.java
src/org/vitrivr/cineast/api/websocket/handlers/abstracts/AbstractWebsocketMessageHandler.java
src/org/vitrivr/cineast/api/websocket/handlers/queries/AbstractQueryMessageHandler.java
src/org/vitrivr/cineast/core/config/QueryConfig.java
src/org/vitrivr/cineast/core/data/MediaType.java
src/org/vitrivr/cineast/core/data/messages/query/Query.java
src/org/vitrivr/cineast/core/data/messages/query/QueryComponent.java
src/org/vitrivr/cineast/core/data/messages/query/QueryTerm.java
src/org/vitrivr/cineast/core/db/cottontaildb/CottontailMessageBuilder.java
src/org/vitrivr/cineast/core/db/cottontaildb/CottontailSelector.java
src/org/vitrivr/cineast/core/db/cottontaildb/CottontailWrapper.java
src/org/vitrivr/cineast/core/db/cottontaildb/CottontailWriter.java
src/org/vitrivr/cineast/core/features/abstracts/SolrTextRetriever.java
src/org/vitrivr/cineast/core/importer/vbs2019/GoogleVisionImportHandler.java
src/org/vitrivr/cineast/core/importer/vbs2019/GoogleVisionImporter.java
src/org/vitrivr/cineast/core/runtime/ContinuousQueryDispatcher.java
src/org/vitrivr/cineast/core/util/ContinuousRetrievalLogic.java

This merges all important changes from lsc19 to dev. Theses include mostly small things + the upgrade to the newest cottontail-version.

LSC 19 final merge

---

cineast-core/src/main/java/org/vitrivr/cineast/core/data/raw/CachedDataFactory.java

This stops CachedDataFactory always attempting to create a directory in
the current working directory as a result of the construction of a
default instance. This will fail if that happens to be a read only file
system, as e.g. with Singularity.

Create directory in CachedDataFactory lazily

---

gradle/wrapper/gradle-wrapper.properties

See https://github.com/gradle/gradle/issues/10248

Upgrade gradle to version which supports JDK 14+

---

cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ExtractionCommand.java
cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ImportCommand.java

Fixes issues raised with the optimize flag in #121 including the addition of the optimize flag in the import command.

Fixes and improvements to the extraction/import optimize flag

---

cineast-api/src/main/java/org/vitrivr/cineast/api/messages/query/QueryStage.java
cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailEntityCreator.java
cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailWrapper.java
cineast-core/src/main/java/org/vitrivr/cineast/core/features/RangeBooleanRetriever.java
cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/DatabaseSetupCommand.java
cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/config/ExtractionPipelineConfig.java
cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/util/ContinuousRetrievalLogic.java

Includes:
- new `entityDetails` CottontailWrapper method
- fix to the visibility of the `RangeBooleanRetriever`
- Enables using the `DatabaseSetupCommand` with both cli and non-cli
- Fixes to the default settings of the `ExtractionPipelineConfig`
Only Bugfixes, so patch version bump!

3.0.1: Cherrypicked LSC Changes

---

cineast-api/src/main/java/org/vitrivr/cineast/api/rest/resolvers/FileSystemObjectResolver.java
cineast-core/src/main/java/org/vitrivr/cineast/core/iiif/imageapi/ImageRequest.java

Fixes the remaining java build warnings (fixable from within Cineast).

Fix remaining Java build warnings

---

build.gradle
cineast-core/src/main/java/org/vitrivr/cineast/core/config/DatabaseConfig.java
cineast-core/src/main/java/org/vitrivr/cineast/core/db/DataSource.java
cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailWriter.java
cineast-core/src/main/java/org/vitrivr/cineast/core/features/ProvidedOcrSearch.java
cineast-core/src/test/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailIntegrationDBProvider.java
cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/ImportCommand.java
cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/TextRetrievalCommand.java
cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/config/IngestConfig.java
cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/importer/handlers/JsonDataImportHandler.java
cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/monitoring/ImportTaskMonitor.java

Adding a ProvidedOCR feature which is explicit about being for imported data, adding an option to disable transactions during import

Adding ProvidedOCR feature, option to disable transactions during import

---

cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailEntityCreator.java

This PR adds an index on the `id` column for all entities by default. This is desirable for mlt requests, and for users which seek more information about the features of a given segment.

creating index on id-column by default

---

cineast-core/src/test/java/org/vitrivr/cineast/core/db/DBIntegrationTest.java

#288 got merged prematurely and broke some tests. This PR ensures the texts are correct

Fixing Unit-Tests

---

build.gradle
cineast-api/src/main/java/org/vitrivr/cineast/api/messages/query/TemporalQuery.java

Removed explicit requirement for message type and implicit requirement for temporal query config from temporal query.

Zero-Config REST Temporal Queries

---

README.md
cineast-core/src/main/java/org/vitrivr/cineast/core/data/MediaType.java
cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/image/ImageSequenceSegmenter.java
cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/run/GenericExtractionItemHandler.java
gradle/wrapper/gradle-wrapper.properties

Minor bugfixes to ensure a smooth process for users who try to extract & retrieve data with the default config & README

Cleanup & bugfixes for default setup
